# Generated by Django 3.0.7 on 2020-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
    ]
